{"name": "Get account by id invalid -- @1.3 ", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 400 to equal 404\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 41, in step_impl\n    expect(int(status_code)).to_equal(context.response.status_code)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 173, in to_equal\n    ensure(self.value == other, True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "steps": [{"name": "Given I set up a \"GET\" request to \"/accounts/{1a2s}\" endpoint", "status": "passed", "start": 1556562142397, "stop": 1556562142398}, {"name": "When I send the request", "status": "passed", "start": 1556562142398, "stop": 1556562142850}, {"name": "Then I get a \"400\" status code as response", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 400 to equal 404\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 41, in step_impl\n    expect(int(status_code)).to_equal(context.response.status_code)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 173, in to_equal\n    ensure(self.value == other, True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "start": 1556562142850, "stop": 1556562142852}, {"name": "And I should see a messages error: The id isn't valid", "status": "skipped", "start": 1556562142852, "stop": 1556562142853}], "parameters": [{"name": "id", "value": "1a2s"}], "start": 1556562142396, "stop": 1556562142853, "uuid": "84bf455c-5f18-4630-9adb-78f7a69fa75c", "historyId": "0bb8b5215b446b6b2e7876018b891420", "labels": [{"name": "tag", "value": "functional_get_negative"}, {"name": "tag", "value": "account"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional test cases negative of read for account by id"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}