{"name": "Cannot update the \"point scale\" of project strange values -- @1.5 ", "status": "passed", "steps": [{"name": "Given I set up a \"PUT\" request to \"/projects/{proj_id}\" endpoint", "status": "passed", "start": 1556562445675, "stop": 1556562445676}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "d904c533-a399-4ed0-92df-e6e846abe58b-attachment.txt", "type": "text/plain"}], "start": 1556562445676, "stop": 1556562445679}, {"name": "When I send the request", "status": "passed", "start": 1556562445680, "stop": 1556562446179}, {"name": "Then I get a \"400\" status code as response", "status": "passed", "start": 1556562446180, "stop": 1556562446181}, {"name": "And I verify the general_problem of error is: \"You can't have duplicate point values.\"", "status": "passed", "start": 1556562446181, "stop": 1556562446183}], "parameters": [{"name": "values", "value": "\"1,2,2,3\""}, {"name": "message", "value": "You can't have duplicate point values."}], "start": 1556562445673, "stop": 1556562446183, "uuid": "42868c24-f6e3-41b7-8656-774ef6b8636a", "historyId": "184ec93b6fbd101ff11c41b29fbfa45f", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "project"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional Test Negative Cases of Update Projects"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}