{"name": "Get account by id that not exist -- @1.1 ", "status": "passed", "steps": [{"name": "Given I set up a \"GET\" request to \"/accounts/{0}\" endpoint", "status": "passed", "start": 1556562143813, "stop": 1556562143813}, {"name": "When I send the request", "status": "passed", "start": 1556562143814, "stop": 1556562144265}, {"name": "Then I get a \"404\" status code as response", "status": "passed", "start": 1556562144265, "stop": 1556562144267}, {"name": "And I should see a messages error: The object you tried to access could not be found.", "status": "passed", "start": 1556562144267, "stop": 1556562144267}], "parameters": [{"name": "id", "value": "0"}], "start": 1556562143811, "stop": 1556562144268, "uuid": "8d72628b-4f61-46bd-9414-7f68ed24b1c8", "historyId": "d4ba24d43a238bfc4d0975a0e33a9c44", "labels": [{"name": "tag", "value": "functional_get_negative"}, {"name": "tag", "value": "account"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional test cases negative of read for account by id"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}