{"name": "Cannot update the \"point scale\" of project strange values -- @1.8 ", "status": "passed", "steps": [{"name": "Given I set up a \"PUT\" request to \"/projects/{proj_id}\" endpoint", "status": "passed", "start": 1556562447194, "stop": 1556562447195}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "917523fb-d5b0-444c-a545-e5599ecbb5f4-attachment.txt", "type": "text/plain"}], "start": 1556562447195, "stop": 1556562447198}, {"name": "When I send the request", "status": "passed", "start": 1556562447198, "stop": 1556562447728}, {"name": "Then I get a \"400\" status code as response", "status": "passed", "start": 1556562447728, "stop": 1556562447730}, {"name": "And I verify the general_problem of error is: \"This is not a valid custom point scale.\"", "status": "passed", "start": 1556562447730, "stop": 1556562447732}], "parameters": [{"name": "values", "value": "\"word,0,1\""}, {"name": "message", "value": "This is not a valid custom point scale."}], "start": 1556562447193, "stop": 1556562447732, "uuid": "ad7e66c9-1c11-4387-ba94-693d4be335ac", "historyId": "a0c6a4fae73b28784a6b68645d6b4cfb", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "project"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional Test Negative Cases of Update Projects"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}