{"name": ": Cannot update the name of project with the same existent project", "status": "passed", "steps": [{"name": "Given I set up a \"PUT\" request to \"/projects/{proj_id}\" endpoint", "status": "passed", "start": 1556562438577, "stop": 1556562438578}, {"name": "And I get a existent project", "status": "passed", "start": 1556562438578, "stop": 1556562439245}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "80e7b197-205d-43d3-a6d5-ece02c2c0b80-attachment.txt", "type": "text/plain"}], "start": 1556562439246, "stop": 1556562439250}, {"name": "When I send the request", "status": "passed", "start": 1556562439250, "stop": 1556562439790}, {"name": "Then I get a \"400\" status code as response", "status": "passed", "start": 1556562439790, "stop": 1556562439792}, {"name": "And I verify the general_problem of error is: \"The project name you entered is already taken.\"", "status": "passed", "start": 1556562439792, "stop": 1556562439793}], "start": 1556562438575, "stop": 1556562439807, "uuid": "672a82f0-a76a-4fed-aa37-f2d652887bf8", "historyId": "bc83140ddae7b86f8cc68e7e86c19595", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "project"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional Test Negative Cases of Update Projects"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}