{"name": "Get account by id invalid -- @1.5 ", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 400 to equal 404\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 41, in step_impl\n    expect(int(status_code)).to_equal(context.response.status_code)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 173, in to_equal\n    ensure(self.value == other, True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "steps": [{"name": "Given I set up a \"GET\" request to \"/accounts/{12 3}\" endpoint", "status": "passed", "start": 1556562143356, "stop": 1556562143358}, {"name": "When I send the request", "status": "passed", "start": 1556562143358, "stop": 1556562143807}, {"name": "Then I get a \"400\" status code as response", "status": "failed", "statusDetails": {"message": "compare.UnmetExpectation: Expected 400 to equal 404\n", "trace": "  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\project_steps.py\", line 41, in step_impl\n    expect(int(status_code)).to_equal(context.response.status_code)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 173, in to_equal\n    ensure(self.value == other, True, message)\n  File \"c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\compare.py\", line 151, in ensure\n    raise UnmetExpectation(message)\n"}, "start": 1556562143807, "stop": 1556562143809}, {"name": "And I should see a messages error: The id isn't valid", "status": "skipped", "start": 1556562143810, "stop": 1556562143810}], "parameters": [{"name": "id", "value": "12 3"}], "start": 1556562143354, "stop": 1556562143810, "uuid": "035d2c4f-6de7-43e2-be76-a094d34f99ab", "historyId": "ce0a0c5b729db7347e4a4bb9078a7ddb", "labels": [{"name": "tag", "value": "functional_get_negative"}, {"name": "tag", "value": "account"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional test cases negative of read for account by id"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}