{"name": "Cannot update the \"point scale\" of project strange values -- @1.4 ", "status": "passed", "steps": [{"name": "Given I set up a \"PUT\" request to \"/projects/{proj_id}\" endpoint", "status": "passed", "start": 1556562445148, "stop": 1556562445149}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "b6cbfc15-5784-4624-b952-91debb5892f0-attachment.txt", "type": "text/plain"}], "start": 1556562445150, "stop": 1556562445152}, {"name": "When I send the request", "status": "passed", "start": 1556562445152, "stop": 1556562445663}, {"name": "Then I get a \"400\" status code as response", "status": "passed", "start": 1556562445663, "stop": 1556562445667}, {"name": "And I verify the general_problem of error is: \"This is not a valid custom point scale.\"", "status": "passed", "start": 1556562445667, "stop": 1556562445668}], "parameters": [{"name": "values", "value": "\"[1,2]\""}, {"name": "message", "value": "This is not a valid custom point scale."}], "start": 1556562445146, "stop": 1556562445669, "uuid": "b7485c8d-d4c8-4bff-a3ac-a99ccdef09f4", "historyId": "3ef510effb5f939157d5d74d083c668f", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "project"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional Test Negative Cases of Update Projects"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}