{"name": "Cannot update the integer param of \"number_of_done_iterations_to_show\" of project with extreme values -- @1.3 ", "status": "passed", "steps": [{"name": "Given I set up a \"PUT\" request to \"/projects/{proj_id}\" endpoint", "status": "passed", "start": 1556562460702, "stop": 1556562460703}, {"name": "And I set up the data", "status": "passed", "attachments": [{"name": ".text", "source": "756d9859-2a3b-4997-953a-c1b4299abdbf-attachment.txt", "type": "text/plain"}], "start": 1556562460703, "stop": 1556562460704}, {"name": "When I send the request", "status": "passed", "start": 1556562460704, "stop": 1556562461145}, {"name": "Then I get a \"400\" status code as response", "status": "passed", "start": 1556562461145, "stop": 1556562461148}, {"name": "And I verify the general_problem of error is: \"'number_of_done_iterations_to_show' must be an integer value\"", "status": "passed", "start": 1556562461148, "stop": 1556562461149}], "parameters": [{"name": "number", "value": "\"letter\""}, {"name": "message", "value": "'number_of_done_iterations_to_show' must be an integer value"}], "start": 1556562460701, "stop": 1556562461150, "uuid": "09939e10-e9d1-47d4-8dcd-f9db623e0fc1", "historyId": "0e172c5249076ec2becacfd40cd3573b", "labels": [{"name": "tag", "value": "negative"}, {"name": "tag", "value": "project"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Functional Test Negative Cases of Update Projects"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}